# Site settings
title: Beverley Yeo
description: Personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beverleyy.github.io" # the base hostname & protocol for your site
unpublished: true

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass
  - add_dates.py
  - _projects/template.md

include:
  - "_pages"

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      img_path: "/assets/images"
  - scope:
      type: projects
      path: ""
    values:
      page_generated: false
      published: false
  - scope:
      type: playground
      path: ""
    values:
      page_generated: true
      published: true

collections:
  projects:
    output: true
    permalink: /:collection/:title/
  playground:
    output: true
    permalink: /:collection/:title/
