# Site settings
title: Beverley Yeo
description: Personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beverleyy.github.io" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass
  - add_dates.py
  - _projects/template.md

include:
  - "_pages"

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  projects:
    output: false
  websites:
    output: true
    permalink: /:collection/:title/
  builds:
    output: false
